### ISSUE TITLE
Mouse focus issues

### ISSUE THREAD

**Issue by wheybags** [vurtun/nuklear#432] opened 2017-05-09 16:53 UTC
I'm doing evaluation for using Nuklear at my company, and I've found a couple of issues with mouse control in the demo programs.

In the basic demo, window resizing seems to lose focus when you drag the resizing to the top right, as illiustrated below.
Shown after is me resizing a mintty window, showing the bheaviour I would expect.
![window_resize](https://cloud.githubusercontent.com/assets/1093274/25862474/1451919c-34e0-11e7-8f0f-c679ad166d2f.gif)

(The scrollbar also screws up, but that's not too big a deal)

In the node editor demo, mouse focus goes a bit wonky when I drag one node over another:
![node_drag](https://cloud.githubusercontent.com/assets/1093274/25862512/396f28ae-34e0-11e7-8d4b-101d0f32e654.gif)

We will be wanting resizing and dragging over, so do you have any recommendations on how we can avoid these issues?

Side note: I'm also thinking of using this in my side project, freeablo (https://github.com/wheybags/freeablo)

**Comment by vurtun** [comment] 2017-05-09 18:16
Thanks for the issue and your detailed bug descriptions.

> In the basic demo, window resizing seems to lose focus when you drag the resizing to the top right, as illiustrated below.

Small bug caused by wrongfully not handling case of hitting minimum window size while dragging. Should be fixed in commit: 9ed3eeec8d248d961a36e34f7b9336da2ac7af24.

> (The scrollbar also screws up, but that's not too big a deal)

Interestingly only a bug in OpenGL demos and not X11. Seems like some clipping rectangle bug. Will take a closer look.

> In the node editor demo, mouse focus goes a bit wonky when I drag one node over another:

That should be more a node editor specific problem since I did not implement correct overlapping support for custom nodes. `nk_group_xxx` has no persistent state for z-order only scrollbar offset. So if I would actually implement a node editor I would internally add the state or handle it inside the node editor directly.

**Closed** 2017-05-10 05:45 UTC

**Comment by wheybags** [comment] 2017-05-10 07:56
Wow, talk about fast turnaround! Thanks @vurtun!

**Comment by wheybags** [comment] 2017-05-10 10:01
So, there is still a much smaller issue, in that the mouse position relative to the dragging triangle is offset by the amount ove the left/top of the window you went while dragging. IE, the window starts growing immediately when you drag left, not when you drag all the way back to minimum size and then drag further left.
Gif example: 
![nk_drag_gif](https://cloud.githubusercontent.com/assets/1093274/25893511/f9a7efe0-356f-11e7-86fd-8931d2b1a608.gif)

**Comment by vurtun** [comment] 2017-05-10 10:27
Thanks found the problem and fixed it. Will push commit it as soon as I get home.

**Comment by wheybags** [comment] 2017-05-10 10:36
Nice, thanks again!
