### ISSUE TITLE
Demo example looks garbled under Wayland with GLFW3 and OpenGL2

### ISSUE THREAD

**Issue by wasamasa** [vurtun/nuklear#174] opened 2016-07-04 09:11 UTC
X11 with i3wm:

![](http://i.imgur.com/IJaBFxr.png)

Wayland with orbment:

![](http://i.imgur.com/F8AUJXi.png)

This can be "fixed" by specifying a hint of zero for `GLFW_ALPHA_BITS` before creating the window.  I suspect the proper fix would be not relying on the alpha bits to be zeroed as compositors under Wayland can assume that they don't need to be zeroed (see orbment) or that they need to be (see Weston).

**Comment by vurtun** [comment] 2016-07-28 08:24
Thanks for the issue. I am not 100% what you mean. As far as know every color's alpha byte is set to 255 if there is no transparency or do you mean for the vertex buffer output? If so then I probably forgot to set the correct bits inside the 32-bit color value. I will check it out and push a fix ASAP.

**Comment by wasamasa** [comment] 2016-07-28 08:28
The colors look fine to me, so if anything, the vertex buffer output should be the culprit.

**Comment by vurtun** [comment] 2016-07-28 08:44
Hm the function to convert from `nk_color` to `uint32_t` is here:
```c
NK_API nk_uint
nk_color_u32(struct nk_color in)
{
    nk_uint out = (nk_uint)in.r;
    out |= ((nk_uint)in.g << 8);
    out |= ((nk_uint)in.b << 16);
    out |= ((nk_uint)in.a << 24);
    return out;
}
```
But I don't see anything wrong with it at the moment. The correct alpha value is shifted to the correct position. It is also strange that only the border of all draw calls (even look like only rectangle drawing calls) have the wrong color so it is unlikely that wayland has a different color format.

**Comment by linkmauve** [comment] 2016-07-28 19:14
This will be fixed with https://github.com/glfw/glfw/pull/788 btw.

And the issue is that not every pixel has alpha of 255, other platforms create an XRGB surface are not affected by this.

**Closed** 2017-04-12 19:01 UTC
Labels: bug
