### ISSUE TITLE
X11 demo fails in X_PolyFillRectangle

### ISSUE THREAD

**Issue by nzjrs** [vurtun/nuklear#65] opened 2016-04-19 07:50 UTC
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  70 (X_PolyFillRectangle)
  Serial number of failed request:  29
  Current serial number in output stream:  102
```

**Comment by vurtun** [comment] 2016-04-19 08:57
I am not an expert with xlib and X11 and I don't have a lot of information to go on here. So do you have all correct libraries installed (even libraries like `libx11-dev`), since this look to me like X11 does not know the command (opcode) to draw a filled rectangle. Since this functionality is not even a extension or other non-specific function I am a little bit surprised.

**Comment by nzjrs** [comment] 2016-04-19 08:58
yip, all deps are installed. It builds fine (with GCC and clang
incidentally)

**Comment by vurtun** [comment] 2016-04-19 09:04
Is there a way to run the debugger and see on which line the problem occurs?. The problem is it works for me which complicates things a lot and does not provide me with any information.

**Comment by nzjrs** [comment] 2016-04-19 09:17
Drawing is async in X (AIUI), so if I step over XFlush it happens at line
150, if I step through then it happens a bit later when X does the drawing.

Not a lot of help sorry.

**Comment by buserror** [comment] 2016-04-19 09:32
All I can do is report the same problem, using debian sid+nvidia driver blobs. The GL examples works just fine.
Too bad, as X11 is nice to have when you are working remotely (x2go, etc)

**Comment by laneslexicon** [comment] 2016-04-19 09:36
I get the same error on FreeBSD. 

Not sure what it is trying to draw, but according to the xlib docs X_PolyFillRectangle ends up as XFillRectangle and this is what I see as the width/height parameters to the function
```
sudo dtrace -n 'pid$target:libX11.so.6.3.0:XFillRectangle:entry { printf("%d/%d",arg5,arg6);}' -c bin/zahnrad
dtrace: description 'pid$target:libX11.so.6.3.0:XFillRectangle:entry ' matched 1 probe
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  70 (X_PolyFillRectangle)
  Serial number of failed request:  29
  Current serial number in output stream:  102
dtrace: pid 5124 exited with status 1
CPU     ID                    FUNCTION:NAME
  2  64032             XFillRectangle:entry 800/600
  2  64032             XFillRectangle:entry 196/29
  2  64032             XFillRectangle:entry 21/21
  2  64032             XFillRectangle:entry 6/4
  2  64032             XFillRectangle:entry 21/34359738389
  2  64032             XFillRectangle:entry 6/34359738372
  2  64032             XFillRectangle:entry 24/34359738372
  2  64032             XFillRectangle:entry 196/34359738535
  2  64032             XFillRectangle:entry 36/34359738372
  2  64032             XFillRectangle:entry 54/34359738370
  2  64032             XFillRectangle:entry 54/34359738370
  2  64032             XFillRectangle:entry 72/34359738371
  2  64032             XFillRectangle:entry 6/34359738374
  2  64032             XFillRectangle:entry 6/34359738374
  2  64032             XFillRectangle:entry 20/34359738386
  2  64032             XFillRectangle:entry 12/34359738370

**Comment by vurtun** [comment] 2016-04-19 09:54
OK this is bad. I will check and test everything to make sure that this will be fixed so far thanks for the information. I will dig into it and see what went wrong.

**Comment by vurtun** [comment] 2016-04-19 10:45
OK I found the problem. I allocate a pixmap to draw into. The pixmap requires the correct size of the window. If a window is resized my demo code will listen for `Expose` and `ConfigureNotify` events and resize the pixmap. I use the i3 tiled window manager so it is guaranteed to resize the window before anything is drawn and the pixmap has the correct size. Could someone test what width and height values are passed to either `nk_xlib_init`, `nk_xlib_create` and `XCreatePixmap`?

**Comment by nzjrs** [comment] 2016-04-19 10:51
I get the 'correct' values passed to XCreatePixmap (the call is
XCreatePixmap(dpy, root, 800, 600, 32);)

but still a crash. Gnome 2 gui

**Closed** 2016-04-19 10:58 UTC

**Comment by vurtun** [comment] 2016-04-19 10:59
OK I hopefully found the problem (it works at least for me if I deactivate the resizing code). Please check if it work now or if I have to look further.

**Comment by nzjrs** [comment] 2016-04-19 10:59
Yip, fixed and working for me. Thanks

**Comment by laneslexicon** [comment] 2016-04-19 11:03
Fixed  and working on FreeBSD. Thanks

**Comment by vurtun** [comment] 2016-04-19 11:06
Sounds good. Thanks everyone for helping me out here.
