### ISSUE TITLE
Window dragging does not match up with cursor position

### ISSUE THREAD

**Issue by EternityX** [vurtun/nuklear#470] opened 2017-06-26 12:00 UTC
Hi there,

Whenever dragging a window, it will lag way behind the cursor.
Any ideas what would cause this?

Small video demonstrating the issue: 
https://www.youtube.com/watch?v=d6M_yXTib8c

**Comment by dumblob** [comment] 2017-07-16 16:58
Duplicate of https://github.com/vurtun/nuklear/issues/297 (there is a software cursor available for this reason).

**Comment by xissburg** [comment] 2017-07-18 19:20
@dumblob this is not a related issue. In this case it seems the cursor displacement is being scaled down, perhaps because of a high dpi/retina screen.

**Closed** 2018-03-09 16:24 UTC
