### ISSUE TITLE
Split to multiple headers for development

### ISSUE THREAD

**Issue by jimon** [vurtun/nuklear#117] opened 2016-04-30 09:38 UTC
I think that having one header deployment is the best way to ship C/C++ libraries (aka [stb](https://github.com/nothings/stb) way), but it makes development a bit clumsy in a way. In my case I would like to contribute to the library, but having 15kloc file is just too bulky to work on and takes time to figure out the mental model behind the code. In some other projects like [tigr](https://bitbucket.org/rmitton/tigr/src) and [buildfox](https://github.com/beardsvibe/buildfox) they have source as separate files which gets amalgamated into final files in the end.

Would be nice to have nuklear source divided across multiple files just for sake of making development a bit easier.

**Comment by dumblob** [comment] 2016-04-30 12:10
Good point. I would though leave this decision on the main developer. I can just add one more well-known example using amalgamation - [SQLite](https://www.sqlite.org/amalgamation.html ).

**Comment by vurtun** [comment] 2016-05-02 08:39
> Would be nice to have nuklear source divided across multiple files just for sake of making development a bit easier.

Making this library a single header file is probably one of the most controversial topics for this library. I spend a lot of time thinking about it, wrote other single header libraries and changed from multiple files to single header file back and forth at least two times for this library. So it is not like I picked single header without thinking or weighting my options. In general when there are multiple options I at least want to try both out if I have the time.

So what I am going to say now comes from a mindset I currently have and developed over some time. I don't know if it is the right decision and in the long term I hope to get more insight. Another heads up I am not really good at articulating so try to bear with me.

If you really get down to the reason of single header file libraries it is a trade off and different people prefer different advantages and can life with different disadvantages. In a perfect world I would do the same I did inside my library itself and let users decide what they do. For example I would have multiple files and provide a script to collapse it into a single header library. So I would have the best of both worlds. The problem is it would require a lot of work to make both cases work and I don't want to maintain that mess (and in the end I will be the one having to maintain it even if I wouldn't write it the script myself since people are fast to make changes or add things to a repository but would never invest time maintaining). 

So the perfect world is not something I could maintain. So we end up having to decide between single header and `2+` files. A lot of advantages are already pretty much known from what Sean Barrett reasoned: https://github.com/nothings/stb. Seans reasons are mainly usability related and singe header libraries are more like a work around of windows and `C` limitations.

While I absolutely agree with all of his points I also noticed additional advantages beside usability (he knows them as well) which are in my opinion even more interesting. Which is module (in this particular instance I would define module as a single header file) based library control close to ML functors (parameterized modules). In short you basically can define the behavior and implementation of a library by defining different preprocessor flags, which I do to some extend (There is a lot more you can do with it than I do in this library and I am still testing how far you can go but so far it seems quite powerful). 

So basically what I get out of single header library is usability and an easy way to leave control of the library in the hand of the user. At least for smaller libraries I would stop here and there wouldn't be much counter argument to made here.

The biggest problem however is the library size with ~15k LOC. Now we reach a critical mass. A library change will force the user to recompile his/her project (can be worked around) and it hits harder for bigger libraries. Furthermore it will become harder to change since only the author knows the code layout and it is quite hard to dive into the code since you don't know where everything is. Another argument could be made to just create multiple single header files (what I already do for library + backend code) but this already has another set of up- and downsides.

So to stop here (I already wrote way to much) in the end I had to decide between usability and having people to contribute. Personally I did not anticipate how this library would get. Honestly I just wanted to write this library to have something on my resume to show for to get a job. So the decision at that time was ease of use so at least those who try it out will have a quick jump in since having people to contribute (with code) was not something I dared to think about. Will I change it now? Probably not. I like it the way it is at this moment. It is not perfect but in the end at least for libraries everything can only be perfect to some but not for everyone.

**Comment by jimon** [comment] 2016-05-02 08:54
@vurtun I think as a library user I really appreciate having one header, and as a library developer, well, not really. The point is not recompilation experience or anything, but actual library development experience. In current form the library is not so easy to contribute/modify.

Maybe the problem I'm facing is not one/2+ files, but contribution/improvement itselfююю To understand current code layout I need to use editors with aggressive code folding, and it still takes time to build mental model.

Probably this could be improved if we make some sort of more generic code overview (diagrams or something) about library internals?

**Comment by vurtun** [comment] 2016-05-02 11:14
> Probably this could be improved if we make some sort of more generic code overview (diagrams or something) about library internals?

In general yes. Is it a top priority for me? no. At the moment I don't know a good way of doing it in a good way. I mean I have sections and modules inside the single file. So it is not like everything is just one big block of code which is intertwined. What could be an idea is to basically write like a table of content with module/section name, code lines it begins and number of lines.

**Comment by dumblob** [comment] 2016-05-04 20:46
>What could be an idea is to basically write a table of content with module/section name, code lines it begins and number of lines?

Hm, for the purpose @jimon mentioned this wouldn't help much (as it's very close to what folding already does). I think this is rather about block diagram showing "flow" of the code or just dependence hierarchy - maybe similar to this:

![singlechanneldvbcj83modulator](https://cloud.githubusercontent.com/assets/2451044/15028591/e1830eda-1249-11e6-8a39-0cac25a913de.png)

**Comment by malv-c** [comment] 2016-05-05 08:51
maybe a awk script can split to dev
some functions could be don in asm

**Comment by vurtun** [comment] 2016-05-05 11:00
@dumblob I know block diagrams but they are so much work and I don't have enough time to do any of that.

**Comment by dumblob** [comment] 2016-05-06 09:08
@jimon would a [call graph](https://en.wikipedia.org/wiki/Call_graph#Software ) help you? Call graph generation is nowadays supported by many IDEs, so it should be easy to use for those, who don't want to spend 1 hour with reading the Nuklear source to get an overview.

**Comment by jimon** [comment] 2016-05-06 09:15
@dumblob probably, I've decided to take it slow and just digest the code one step on a time, folding kinda helps, but it takes time to recreate the mental model in my head :) Though this should be improved if we want people to collaborate on the project internals.

**Comment by dumblob** [comment] 2016-05-06 09:46
@jimon on the other hand, maybe it would make sense to leave it as it is as a proof, that the potential contributor is enough motivated to provide good code.

**Comment by rokups** [comment] 2016-08-03 17:56
I vote for splitting lib up in separate files. There are two problems i encountered.. Some IDEs have problem with big files like getting slow or just refusing to provide advanced features for them. Also since implementation is disabled by default using preprocessor smarter IDEs tend to consider that section as being unused and thus also do not provide things like code completion, error checking etc..

I think sqlite guys did great by having lib done in separate files while build system creates single big `sqlite.c` that is easy to use. Even if header and implementation were split for starters that would be helpful, but i would prefer seeing more code split up.

**Comment by dumblob** [comment] 2016-08-03 18:30
>Some IDEs have problem with big files like getting slow or just refusing to provide advanced features for them.

20000 lines of code is an issue? It's 2016 (actually, this wasn't any problem even 20 years ago)! Personally I would immediately filed a bug report on such IDE (god bless you if you're talking about Atom, which will never be fast enough because of a totally wrong choice of implementation technology).

>Also since implementation is disabled by default using preprocessor smarter IDEs tend to consider that section as being unused and thus also do not provide things like code completion, error checking etc..

Truly *smarter IDE*s provide means to disable this default behavior (e.g. on a per-file basis).

**Comment by vurtun** [comment] 2016-08-03 18:35
@rokups I would say the following about this topic (in addition to the big post I did above), if you can provide me with a script that works 100% of the time and takes multiple files and generates one single header library file out of it I will do it, otherwise no.

**Comment by warmwaffles** [comment] 2016-08-03 18:42
I am on the insane side of the spectrum, and like to split each function out into a separate file. Avoid using `#ifdef WIN32` and copy the two implementations to their respective directories. I feel it forces you to keep your stuff modular and show clear definitions. 

```
includes/
  nuklear.h
src/
  all/
  win/
  osx/
  linux/
```

This is also a nightmare for people who don't use CMake or don't want to go through the hassle of figuring out what definitions need to be enabled to make it compile right.

But in the end, it is @vurtun's library, and he is ultimately the person who has to live with it and approve prs. What ever he is comfortable with, should take precedence.

**Comment by dumblob** [comment] 2016-08-03 19:35
>This is also a nightmare for people who don't use CMake or don't want to go through the hassle of figuring out what definitions need to be enabled to make it compile right.

I think splitting into separate files wouldn't help much (if at all) in this case. Anyway, this can be IMHO easily solved by using some standard documentation markup - Doxygen, Sphinx (now newly used even in the whole Linux kernel!), etc. In the worst case, it's quite easy to add one or two grep/sed/awk/... commands to the Nuklear `README.md` filltering out the most important definitions and their comments from `nuklear.h` to get a precise overview.

**Comment by rokups** [comment] 2016-08-04 09:43
> I am on the insane side of the spectrum, and like to split each function out into a separate file. Avoid using `#ifdef WIN32` and copy the two implementations to their respective directories. I feel it forces you to keep your stuff modular and show clear definitions. 

Yes you are.. Because for starters this library does not have a single platform-specific `#ifdef` and it is completely platform-independent. And even if there were such `#ifdef` they usually alter function behaviour in minor ways which basically means lots of same code being copied in multiple places. Hurts maintainability. And every function in it's own file.. it would just make navigation way harder than it is now with no real benefits. I mean heck.. Gazillion of files most of which would be less than 10 lines long, sounds like fun right?

@vurtun to make things simpler say lib is split to `src/nuklear.h` and `src/nuklear.c`, and `.c` file includes header on the very first file. `.c` file also does not have `NK_IMPLEMENTATION` guard. Then:

    cat src/nuklear.h > nuklear.h                  # add header
    echo '#ifdef NK_IMPLEMENTATION' >> nuklear.h   # add implementation guard begin
    sed '1d' src/nuklear.c >> nuklear.h            # remove first line (include) and add source
    echo '#endif' >> nuklear.h                     # add implementation guard end

This would work 100% of the time and ease possible development considerably while allowing to take advantage of our tools. The way you put together this library is so forgiving that even if we split up `nuklear.c` further separating code say by widget type then we could follow exactly same procedure and even order of appending `.c` files to amalgamated header would not matter and for sake of consistency files could be alphabetically sorted before concatenating them.
The problem i see with this however is another dependency. Should this process use gnu tools, python script? That wont build on windows. Have `build.sh` for unixes and `build.bat` for windows? That could work and be low maintenance really (like write-once and forget). Or maybe there is better way that would work on all platforms?

**Comment by dumblob** [comment] 2016-08-04 10:39
@rokups I can see your point. If it's really not a general `#ifdef` problem (as I understood from the previous discussion), but rather solely one specific `#ifdef NK_IMPLEMENTATION` problem, then the proposed solution is a perfect one.

Why? Because we don't have to introduce any new dependency for users - it's enough, if each time a developer runs git commit, a pre-commit git hook will run POSIX shell script performing the above steps (thus effectively making an "amalgamated" copy). This way the burden of the POSIX shell dependency is transfered to developers for whom it's not an issue ([neither on Windows](https://blogs.windows.com/buildingapps/2016/08/02/windows-10-anniversary-update-sdk-14393/)).

**Comment by vurtun** [comment] 2016-08-04 12:42
@rokups I will not split nuklear into a single `.h` and `.c` that would be retarded and no different to what it is now. So far what I heard people what want is multiple `.h` and `.c` files for development and a single `.h` for deploying like in SQLite. This part I get but just separating into single `.h` and `.c` makes no difference to what I have now.

This whole thread is going in a loop and I am considering closing it. I said what needs to happen and why it is a single header so if you want to see it being split full fill my conditions I have for separated files and create a PR. Until then I will stick with a single header file.

**Closed** 2016-11-18 19:14 UTC
Labels: discussion
