### ISSUE TITLE
Render to texture

### ISSUE THREAD

**Issue by ecraven** [vurtun/nuklear#195] opened 2016-08-04 09:58 UTC
Is there a way to render a ui to a texture, instead of onto the screen?
Something like nk_sdl_render, but nk_sdl_render_to_texture?

**Comment by dumblob** [comment] 2016-08-04 10:43
Duplicate of https://github.com/vurtun/nuklear/issues/101 (as clarified in https://github.com/vurtun/nuklear/issues/101#issuecomment-213470695 ).

**Comment by vurtun** [comment] 2016-08-08 08:39
This library does not have a direct way to draw the UI to a texture at the moment (Now that I think about it, it would be interesting to have a optional software renderer in the library along side the vertex buffer). However what you can do at the moment if you are using a graphics library (OpenGL, DirectX, .Vulkan, ...) ist to use a framebuffer and drawing into it. If you are not using a graphics library then you could take the library command output (example: x11, gdi) and draw all shapes by hand into a texture or use a library for that.

**Comment by dumblob** [comment] 2016-08-08 09:22
>Now that I think about it, it would be interesting to have a optional software renderer in the library along side the vertex buffer

Thinking about this, it could be a separate single-header library. Maybe there is already something (I've checked the [clib](https://github.com/clibs/clib/wiki/Packages) repo, but nothing is there) - @kobalicek, do you happen to know about any tiny portable 2D SW rasterizer in C?

**Comment by kobalicek** [comment] 2016-08-08 09:31
Nuclear already embeds stb_truetype, which has its own sw rasterizer.

**Comment by vurtun** [comment] 2016-08-08 10:26
@kobalicek While I agree with you I don't really think stb_truetype was meant for this kind of drawing load/volume, on the other hand why not might be interesting to try it out. Main problem is that I tried to keep the range of drawing primitives minimal which results in a lot of overdraw which is probably quite deadly for a software renderer.

**Comment by dumblob** [comment] 2016-08-08 10:42
I made a short source code survey on GitHub and found many projects with SW rasterizers. I looked at their sources and only two remained: https://github.com/lecram/libalt and https://github.com/nothings/stb/blob/master/stb_truetype.h .

I'm curious how the stb_truetype will perform (in terms of quality and speed as I've read a little about internals and saw some benchmarks and it's not the fastest solution - it's really focused on font rendering).

**Comment by kobalicek** [comment] 2016-08-08 10:51
@vurtun I know, I just wanted to point out that you already bundle one sw rasterizer. I'm working on Blend2D (blend2d.com), which is a high-performance 2D library written to use CPU capable of rendering UIs, but I guess that's not what you are looking for :)

**Closed** 2016-11-18 18:58 UTC
Labels: discussion, enhancement, question
